# Generated by Django 4.2.4 on 2023-11-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='descripttion',
            new_name='description',
        ),
    ]
